### ISSUE TITLE
Level umap file for Large Terrain Fog Setup Seems Corrupted

### ISSUE THREAD

**Issue by tcrouch199205** [PacktPublishing/Creating-Stunning-Environments-in-Unreal-Engine-5---A-Game-Artist-Bootcamp#1]
I've been trying to troubleshoot this issue for a few hours now, but have not had any success. Essentially, when following along the "Creating Stunning Environments in Unreal Engine 5" tutorial, I get to the section where I need to open the "LandscapeMap.umap" level. However, out of all the levels in the tutorial, this seems to be the only one that refuses to show up in the content drawer. I've tried loading the project in UE5.2/3/4 to no avail. It seems like this particular file is corrupted. Is it possible to reupload this file so that I can continue following along?

**Comment by Sonakshis** [comment]
Hi @tcrouch199205 

It sounds like you're experiencing a frustrating issue with the "LandscapeMap.umap" file not showing up in your Unreal Engine 5 content drawer. This can indeed be an issue if the file is corrupted or missing. Here are some steps you can take to troubleshoot and potentially resolve this issue:
Steps to Troubleshoot the Missing or Corrupted Level File:
Verify File Location:
Ensure the LandscapeMap.umap file is located in the correct directory within your project. It should be in a Maps or Levels folder under your project's Content directory.
Use your file explorer to navigate to the directory and confirm that the file exists.
Check File Integrity:
If the file exists, it might be corrupted. You can try opening it in a text editor to see if it appears intact (though .umap files are binary and may not be human-readable, you might be able to see if the file looks truncated or incomplete).
Reimport the File:
Sometimes, re-importing the file into Unreal Engine can help. You can do this by right-clicking in the Content Drawer and selecting "Import" to bring in the LandscapeMap.umap file again.
Validate the Project:
Run a project validation to ensure that all assets are correctly referenced and not causing issues. Go to File > Validate Data in Unreal Engine.
Check for Hidden Files:
In some cases, the file might be hidden or not visible due to filter settings. Ensure that your content browser is set to show all files and that no filters are hiding the file.
Rebuild Project:
Try rebuilding the project. Sometimes, a full rebuild can resolve issues with missing or corrupted files. Go to File > Rebuild.
Check Unreal Engine Logs:
Look at the output log for any error messages related to the LandscapeMap.umap. This can provide clues about why the file isn’t loading.

We have also update the code files on GitHub: https://github.com/PacktPublishing/Creating-Stunning-Environments-in-Unreal-Engine-5---A-Game-Artist-Bootcamp
